[package]
name = "individual_swap"
type = "bin"
authors = [""]

[dependencies]
aztec = { path = "../../../aztec-packages/noir-projects/aztec-nr/aztec" }
protocol_types = { path = "../../../aztec-packages/noir-projects/noir-protocol-circuits/crates/types" }
