[package]
name = "token_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-packages/noir-projects/aztec-nr/aztec" }
uint_note = { path = "../../../aztec-packages/noir-projects/aztec-nr/uint-note" }
compressed_string = { path = "../../../aztec-packages/noir-projects/aztec-nr/compressed-string" }
balance_set = { path = "../../../aztec-packages/noir-projects/aztec-nr/balance-set" }
