[package]
name = "swap_summary_tree"
type = "bin"
authors = [""]

[dependencies]
bb_proof_verification = { path = "../../../aztec-packages/barretenberg/noir/bb_proof_verification" }
protocol_types = { path = "../../../aztec-packages/noir-projects/noir-protocol-circuits/crates/types" }
